name: Continuous Integration
on:
  push:
    branches:
    - main
    paths:
    - '!exercises/**'
    - '**'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python v3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: bash -e project/tests.sh